export interface CurrencyItem {
  name: string;
  iso2: string;
  iso3: string;
  countries: string[];
  symbol: string;
}


export const currencyDetailsMap: Record<string,CurrencyItem> = {
  AED: { name: "United Arab Emirates Dirham", iso2: "AE", iso3: "AED", countries: ["United Arab Emirates"], symbol: "د.إ" },
  AFN: { name: "Afghan Afghani", iso2: "AF", iso3: "AFN", countries: ["Afghanistan"], symbol: "؋" },
  ALL: { name: "Albanian Lek", iso2: "AL", iso3: "ALL", countries: ["Albania"], symbol: "L" },
  AMD: { name: "Armenian Dram", iso2: "AM", iso3: "AMD", countries: ["Armenia"], symbol: "֏" },
  ANG: { name: "Netherlands Antillean Guilder", iso2: "CW", iso3: "ANG", countries: ["Curaçao", "Sint Maarten"], symbol: "ƒ" },
  AOA: { name: "Angolan Kwanza", iso2: "AO", iso3: "AOA", countries: ["Angola"], symbol: "Kz" },
  ARS: { name: "Argentine Peso", iso2: "AR", iso3: "ARS", countries: ["Argentina"], symbol: "$" },
  AUD: { name: "Australian Dollar", iso2: "AU", iso3: "AUD", countries: ["Australia", "Kiribati", "Nauru", "Tuvalu"], symbol: "$" },
  AWG: { name: "Aruban Florin", iso2: "AW", iso3: "AWG", countries: ["Aruba"], symbol: "ƒ" },
  AZN: { name: "Azerbaijani Manat", iso2: "AZ", iso3: "AZN", countries: ["Azerbaijan"], symbol: "₼" },
  BAM: { name: "Bosnia and Herzegovina Convertible Mark", iso2: "BA", iso3: "BAM", countries: ["Bosnia and Herzegovina"], symbol: "KM" },
  BBD: { name: "Barbadian Dollar", iso2: "BB", iso3: "BBD", countries: ["Barbados"], symbol: "$" },
  BDT: { name: "Bangladeshi Taka", iso2: "BD", iso3: "BDT", countries: ["Bangladesh"], symbol: "৳" },
  BGN: { name: "Bulgarian Lev", iso2: "BG", iso3: "BGN", countries: ["Bulgaria"], symbol: "лв" },
  BHD: { name: "Bahraini Dinar", iso2: "BH", iso3: "BHD", countries: ["Bahrain"], symbol: ".د.ب" },
  BIF: { name: "Burundian Franc", iso2: "BI", iso3: "BIF", countries: ["Burundi"], symbol: "FBu" },
  BMD: { name: "Bermudian Dollar", iso2: "BM", iso3: "BMD", countries: ["Bermuda"], symbol: "$" },
  BND: { name: "Brunei Dollar", iso2: "BN", iso3: "BND", countries: ["Brunei Darussalam", "Singapore"], symbol: "$" },
  BOB: { name: "Boliviano", iso2: "BO", iso3: "BOB", countries: ["Bolivia"], symbol: "Bs." },
  BRL: { name: "Brazilian Real", iso2: "BR", iso3: "BRL", countries: ["Brazil"], symbol: "R$" },
  BSD: { name: "Bahamian Dollar", iso2: "BS", iso3: "BSD", countries: ["Bahamas"], symbol: "$" },
  BTN: { name: "Bhutanese Ngultrum", iso2: "BT", iso3: "BTN", countries: ["Bhutan"], symbol: "Nu." },
  BWP: { name: "Botswana Pula", iso2: "BW", iso3: "BWP", countries: ["Botswana"], symbol: "P" },
  BYR: { name: "Belarusian Ruble (old)", iso2: "BY", iso3: "BYR", countries: ["Belarus"], symbol: "Br" },
  BZD: { name: "Belize Dollar", iso2: "BZ", iso3: "BZD", countries: ["Belize"], symbol: "$" },
  CAD: { name: "Canadian Dollar", iso2: "CA", iso3: "CAD", countries: ["Canada"], symbol: "$" },
  CDF: { name: "Congolese Franc", iso2: "CD", iso3: "CDF", countries: ["Democratic Republic of the Congo"], symbol: "FC" },
  CHF: { name: "Swiss Franc", iso2: "CH", iso3: "CHF", countries: ["Switzerland", "Liechtenstein"], symbol: "Fr" },
  CLP: { name: "Chilean Peso", iso2: "CL", iso3: "CLP", countries: ["Chile"], symbol: "$" },
  CNY: { name: "Chinese Yuan", iso2: "CN", iso3: "CNY", countries: ["China"], symbol: "¥" },
  COP: { name: "Colombian Peso", iso2: "CO", iso3: "COP", countries: ["Colombia"], symbol: "$" },
  CRC: { name: "Costa Rican Colón", iso2: "CR", iso3: "CRC", countries: ["Costa Rica"], symbol: "₡" },
  CUP: { name: "Cuban Peso", iso2: "CU", iso3: "CUP", countries: ["Cuba"], symbol: "$" },
  CVE: { name: "Cape Verdean Escudo", iso2: "CV", iso3: "CVE", countries: ["Cabo Verde"], symbol: "$" },
  CZK: { name: "Czech Koruna", iso2: "CZ", iso3: "CZK", countries: ["Czech Republic"], symbol: "Kč" },
  DKK: { name: "Danish Krone", iso2: "DK", iso3: "DKK", countries: ["Denmark", "Faroe Islands", "Greenland"], symbol: "kr" },
  DOP: { name: "Dominican Peso", iso2: "DO", iso3: "DOP", countries: ["Dominican Republic"], symbol: "$" },
  DZD: { name: "Algerian Dinar", iso2: "DZ", iso3: "DZD", countries: ["Algeria"], symbol: "د.ج" },
  EGP: { name: "Egyptian Pound", iso2: "EG", iso3: "EGP", countries: ["Egypt"], symbol: "£" },
  ERN: { name: "Eritrean Nakfa", iso2: "ER", iso3: "ERN", countries: ["Eritrea"], symbol: "Nfk" },
  ETB: { name: "Ethiopian Birr", iso2: "ET", iso3: "ETB", countries: ["Ethiopia"], symbol: "Br" },
  EUR: { name: "Euro", iso2: "EU", iso3: "EUR", countries: [
    "Austria", "Belgium", "Croatia", "Cyprus", "Estonia", "Finland",
    "France", "Germany", "Greece", "Ireland", "Italy", "Latvia",
    "Lithuania", "Luxembourg", "Malta", "Netherlands", "Portugal",
    "Slovakia", "Slovenia", "Spain"
  ], symbol: "€" },
  FJD: { name: "Fijian Dollar", iso2: "FJ", iso3: "FJD", countries: ["Fiji"], symbol: "$" },
  FKP: { name: "Falkland Islands Pound", iso2: "FK", iso3: "FKP", countries: ["Falkland Islands"], symbol: "£" },
  GBP: { name: "Pound Sterling", iso2: "GB", iso3: "GBP", countries: ["United Kingdom", "Jersey", "Guernsey", "Isle of Man"], symbol: "£" },
  GEL: { name: "Georgian Lari", iso2: "GE", iso3: "GEL", countries: ["Georgia"], symbol: "₾" },
  GHS: { name: "Ghanaian Cedi", iso2: "GH", iso3: "GHS", countries: ["Ghana"], symbol: "₵" },
  GIP: { name: "Gibraltar Pound", iso2: "GI", iso3: "GIP", countries: ["Gibraltar"], symbol: "£" },
  GMD: { name: "Gambian Dalasi", iso2: "GM", iso3: "GMD", countries: ["Gambia"], symbol: "D" },
  GNF: { name: "Guinean Franc", iso2: "GN", iso3: "GNF", countries: ["Guinea"], symbol: "FG" },
  GTQ: { name: "Guatemalan Quetzal", iso2: "GT", iso3: "GTQ", countries: ["Guatemala"], symbol: "Q" },
  GYD: { name: "Guyanese Dollar", iso2: "GY", iso3: "GYD", countries: ["Guyana"], symbol: "$" },
  HKD: { name: "Hong Kong Dollar", iso2: "HK", iso3: "HKD", countries: ["Hong Kong"], symbol: "$" },
  HNL: { name: "Honduran Lempira", iso2: "HN", iso3: "HNL", countries: ["Honduras"], symbol: "L" },
  HRK: { name: "Croatian Kuna", iso2: "HR", iso3: "HRK", countries: ["Croatia"], symbol: "kn" },
  HTG: { name: "Haitian Gourde", iso2: "HT", iso3: "HTG", countries: ["Haiti"], symbol: "G" },
  HUF: { name: "Hungarian Forint", iso2: "HU", iso3: "HUF", countries: ["Hungary"], symbol: "Ft" },
  IDR: { name: "Indonesian Rupiah", iso2: "ID", iso3: "IDR", countries: ["Indonesia"], symbol: "Rp" },
  ILS: { name: "Israeli New Shekel", iso2: "IL", iso3: "ILS", countries: ["Israel"], symbol: "₪" },
  INR: { name: "Indian Rupee", iso2: "IN", iso3: "INR", countries: ["India", "Bhutan"], symbol: "₹" },
  IQD: { name: "Iraqi Dinar", iso2: "IQ", iso3: "IQD", countries: ["Iraq"], symbol: "ع.د" },
  IRR: { name: "Iranian Rial", iso2: "IR", iso3: "IRR", countries: ["Iran"], symbol: "﷼" },
  ISK: { name: "Icelandic Króna", iso2: "IS", iso3: "ISK", countries: ["Iceland"], symbol: "kr" },
  JMD: { name: "Jamaican Dollar", iso2: "JM", iso3: "JMD", countries: ["Jamaica"], symbol: "$" },
  JOD: { name: "Jordanian Dinar", iso2: "JO", iso3: "JOD", countries: ["Jordan"], symbol: "د.ا" },
  JPY: { name: "Japanese Yen", iso2: "JP", iso3: "JPY", countries: ["Japan"], symbol: "¥" },
  KES: { name: "Kenyan Shilling", iso2: "KE", iso3: "KES", countries: ["Kenya"], symbol: "Sh" },
  KGS: { name: "Kyrgyzstani Som", iso2: "KG", iso3: "KGS", countries: ["Kyrgyzstan"], symbol: "с" },
  KHR: { name: "Cambodian Riel", iso2: "KH", iso3: "KHR", countries: ["Cambodia"], symbol: "៛" },
  KMF: { name: "Comorian Franc", iso2: "KM", iso3: "KMF", countries: ["Comoros"], symbol: "CF" },
  KPW: { name: "North Korean Won", iso2: "KP", iso3: "KPW", countries: ["North Korea"], symbol: "₩" },
  KRW: { name: "South Korean Won", iso2: "KR", iso3: "KRW", countries: ["South Korea"], symbol: "₩" },
  KWD: { name: "Kuwaiti Dinar", iso2: "KW", iso3: "KWD", countries: ["Kuwait"], symbol: "د.ك" },
  KYD: { name: "Cayman Islands Dollar", iso2: "KY", iso3: "KYD", countries: ["Cayman Islands"], symbol: "$" },
  KZT: { name: "Kazakhstani Tenge", iso2: "KZ", iso3: "KZT", countries: ["Kazakhstan"], symbol: "₸" },
  LAK: { name: "Lao Kip", iso2: "LA", iso3: "LAK", countries: ["Laos"], symbol: "₭" },
  LBP: { name: "Lebanese Pound", iso2: "LB", iso3: "LBP", countries: ["Lebanon"], symbol: "ل.ل" },
  LKR: { name: "Sri Lankan Rupee", iso2: "LK", iso3: "LKR", countries: ["Sri Lanka"], symbol: "Rs" },
  LRD: { name: "Liberian Dollar", iso2: "LR", iso3: "LRD", countries: ["Liberia"], symbol: "$" },
  LSL: { name: "Lesotho Loti", iso2: "LS", iso3: "LSL", countries: ["Lesotho"], symbol: "L" },
  LYD: { name: "Libyan Dinar", iso2: "LY", iso3: "LYD", countries: ["Libya"], symbol: "ل.د" },
  MAD: { name: "Moroccan Dirham", iso2: "MA", iso3: "MAD", countries: ["Morocco"], symbol: "د.م." },
  MDL: { name: "Moldovan Leu", iso2: "MD", iso3: "MDL", countries: ["Moldova"], symbol: "L" },
  MGA: { name: "Malagasy Ariary", iso2: "MG", iso3: "MGA", countries: ["Madagascar"], symbol: "Ar" },
  MKD: { name: "Macedonian Denar", iso2: "MK", iso3: "MKD", countries: ["North Macedonia"], symbol: "ден" },
  MMK: { name: "Myanmar Kyat", iso2: "MM", iso3: "MMK", countries: ["Myanmar"], symbol: "Ks" },
  MNT: { name: "Mongolian Tögrög", iso2: "MN", iso3: "MNT", countries: ["Mongolia"], symbol: "₮" },
  MOP: { name: "Macanese Pataca", iso2: "MO", iso3: "MOP", countries: ["Macao"], symbol: "P" },
  MRU: { name: "Mauritanian Ouguiya", iso2: "MR", iso3: "MRU", countries: ["Mauritania"], symbol: "UM" },
  MUR: { name: "Mauritian Rupee", iso2: "MU", iso3: "MUR", countries: ["Mauritius"], symbol: "₨" },
  MVR: { name: "Maldivian Rufiyaa", iso2: "MV", iso3: "MVR", countries: ["Maldives"], symbol: ".ރ" },
  MWK: { name: "Malawian Kwacha", iso2: "MW", iso3: "MWK", countries: ["Malawi"], symbol: "MK" },
  MXN: { name: "Mexican Peso", iso2: "MX", iso3: "MXN", countries: ["Mexico"], symbol: "$" },
  MYR: { name: "Malaysian Ringgit", iso2: "MY", iso3: "MYR", countries: ["Malaysia"], symbol: "RM" },
  MZN: { name: "Mozambican Metical", iso2: "MZ", iso3: "MZN", countries: ["Mozambique"], symbol: "MT" },
  NAD: { name: "Namibian Dollar", iso2: "NA", iso3: "NAD", countries: ["Namibia"], symbol: "$" },
  NGN: { name: "Nigerian Naira", iso2: "NG", iso3: "NGN", countries: ["Nigeria"], symbol: "₦" },
  NIO: { name: "Nicaraguan Córdoba", iso2: "NI", iso3: "NIO", countries: ["Nicaragua"], symbol: "C$" },
  NOK: { name: "Norwegian Krone", iso2: "NO", iso3: "NOK", countries: ["Norway"], symbol: "kr" },
  NPR: { name: "Nepalese Rupee", iso2: "NP", iso3: "NPR", countries: ["Nepal"], symbol: "₨" },
  NZD: { name: "New Zealand Dollar", iso2: "NZ", iso3: "NZD", countries: ["New Zealand", "Cook Islands", "Niue", "Tokelau", "Pitcairn Islands"], symbol: "$" },
  OMR: { name: "Omani Rial", iso2: "OM", iso3: "OMR", countries: ["Oman"], symbol: "ر.ع." },
  PAB: { name: "Panamanian Balboa", iso2: "PA", iso3: "PAB", countries: ["Panama"], symbol: "B/." },
  PEN: { name: "Peruvian Sol", iso2: "PE", iso3: "PEN", countries: ["Peru"], symbol: "S/" },
  PGK: { name: "Papua New Guinean Kina", iso2: "PG", iso3: "PGK", countries: ["Papua New Guinea"], symbol: "K" },
  PHP: { name: "Philippine Peso", iso2: "PH", iso3: "PHP", countries: ["Philippines"], symbol: "₱" },
  PKR: { name: "Pakistani Rupee", iso2: "PK", iso3: "PKR", countries: ["Pakistan"], symbol: "₨" },
  PLN: { name: "Polish Złoty", iso2: "PL", iso3: "PLN", countries: ["Poland"], symbol: "zł" },
  PYG: { name: "Paraguayan Guaraní", iso2: "PY", iso3: "PYG", countries: ["Paraguay"], symbol: "₲" },
  QAR: { name: "Qatari Riyal", iso2: "QA", iso3: "QAR", countries: ["Qatar"], symbol: "ر.ق" },
  RON: { name: "Romanian Leu", iso2: "RO", iso3: "RON", countries: ["Romania"], symbol: "lei" },
  RSD: { name: "Serbian Dinar", iso2: "RS", iso3: "RSD", countries: ["Serbia"], symbol: "дин." },
  RUB: { name: "Russian Ruble", iso2: "RU", iso3: "RUB", countries: ["Russia"], symbol: "₽" },
  RWF: { name: "Rwandan Franc", iso2: "RW", iso3: "RWF", countries: ["Rwanda"], symbol: "FRw" },
  SAR: { name: "Saudi Riyal", iso2: "SA", iso3: "SAR", countries: ["Saudi Arabia"], symbol: "ر.س" },
  SBD: { name: "Solomon Islands Dollar", iso2: "SB", iso3: "SBD", countries: ["Solomon Islands"], symbol: "$" },
  SCR: { name: "Seychellois Rupee", iso2: "SC", iso3: "SCR", countries: ["Seychelles"], symbol: "₨" },
  SDG: { name: "Sudanese Pound", iso2: "SD", iso3: "SDG", countries: ["Sudan"], symbol: "ج.س." },
  SEK: { name: "Swedish Krona", iso2: "SE", iso3: "SEK", countries: ["Sweden"], symbol: "kr" },
  SGD: { name: "Singapore Dollar", iso2: "SG", iso3: "SGD", countries: ["Singapore"], symbol: "$" },
  SHP: { name: "Saint Helena Pound", iso2: "SH", iso3: "SHP", countries: ["Saint Helena", "Ascension Island"], symbol: "£" },
  SLE: { name: "Sierra Leonean Leone", iso2: "SL", iso3: "SLE", countries: ["Sierra Leone"], symbol: "Le" },
  SOS: { name: "Somali Shilling", iso2: "SO", iso3: "SOS", countries: ["Somalia"], symbol: "Sh" },
  SRD: { name: "Surinamese Dollar", iso2: "SR", iso3: "SRD", countries: ["Suriname"], symbol: "$" },
  SSP: { name: "South Sudanese Pound", iso2: "SS", iso3: "SSP", countries: ["South Sudan"], symbol: "£" },
  STN: { name: "São Tomé and Príncipe Dobra", iso2: "ST", iso3: "STN", countries: ["São Tomé and Príncipe"], symbol: "Db" },
  SYP: { name: "Syrian Pound", iso2: "SY", iso3: "SYP", countries: ["Syria"], symbol: "£" },
  SZL: { name: "Eswatini Lilangeni", iso2: "SZ", iso3: "SZL", countries: ["Eswatini"], symbol: "L" },
  THB: { name: "Thai Baht", iso2: "TH", iso3: "THB", countries: ["Thailand"], symbol: "฿" },
  TJS: { name: "Tajikistani Somoni", iso2: "TJ", iso3: "TJS", countries: ["Tajikistan"], symbol: "ЅМ" },
  TMT: { name: "Turkmenistani Manat", iso2: "TM", iso3: "TMT", countries: ["Turkmenistan"], symbol: "m" },
  TND: { name: "Tunisian Dinar", iso2: "TN", iso3: "TND", countries: ["Tunisia"], symbol: "د.ت" },
  TOP: { name: "Tongan Paʻanga", iso2: "TO", iso3: "TOP", countries: ["Tonga"], symbol: "T$" },
  TRY: { name: "Turkish Lira", iso2: "TR", iso3: "TRY", countries: ["Türkiye"], symbol: "₺" },
  TTD: { name: "Trinidad and Tobago Dollar", iso2: "TT", iso3: "TTD", countries: ["Trinidad and Tobago"], symbol: "$" },
  TWD: { name: "New Taiwan Dollar", iso2: "TW", iso3: "TWD", countries: ["Taiwan"], symbol: "$" },
  TZS: { name: "Tanzanian Shilling", iso2: "TZ", iso3: "TZS", countries: ["Tanzania"], symbol: "Sh" },
  UAH: { name: "Ukrainian Hryvnia", iso2: "UA", iso3: "UAH", countries: ["Ukraine"], symbol: "₴" },
  UGX: { name: "Ugandan Shilling", iso2: "UG", iso3: "UGX", countries: ["Uganda"], symbol: "Sh" },
  USD: { name: "United States Dollar", iso2: "US", iso3: "USD", countries: [
    "United States", "American Samoa", "Guam", "Northern Mariana Islands", "Puerto Rico", "U.S. Virgin Islands",
    "Ecuador", "El Salvador", "Panama", "Timor-Leste",
    "British Virgin Islands", "Turks and Caicos Islands",
    "Bonaire", "Sint Eustatius", "Saba",
    "Marshall Islands", "Federated States of Micronesia", "Palau"
  ], symbol: "$" },
  UYU: { name: "Uruguayan Peso", iso2: "UY", iso3: "UYU", countries: ["Uruguay"], symbol: "$" },
  UZS: { name: "Uzbekistan Som", iso2: "UZ", iso3: "UZS", countries: ["Uzbekistan"], symbol: "so'm" },
  VES: { name: "Venezuelan Bolívar", iso2: "VE", iso3: "VES", countries: ["Venezuela"], symbol: "Bs." },
  VND: { name: "Vietnamese Đồng", iso2: "VN", iso3: "VND", countries: ["Vietnam"], symbol: "₫" },
  VUV: { name: "Vanuatu Vatu", iso2: "VU", iso3: "VUV", countries: ["Vanuatu"], symbol: "Vt" },
  WST: { name: "Samoan Tālā", iso2: "WS", iso3: "WST", countries: ["Samoa"], symbol: "T" },
  XAF: { name: "Central African CFA Franc", iso2: "CM", iso3: "XAF", countries: [
    "Cameroon", "Central African Republic", "Chad", "Republic of the Congo", "Equatorial Guinea", "Gabon"
  ], symbol: "Fr" },
  XCD: { name: "East Caribbean Dollar", iso2: "AG", iso3: "XCD", countries: [
    "Antigua and Barbuda", "Dominica", "Grenada", "Saint Kitts and Nevis", "Saint Lucia",
    "Saint Vincent and the Grenadines", "Anguilla", "Montserrat"
  ], symbol: "$" },
  XOF: { name: "West African CFA Franc", iso2: "BJ", iso3: "XOF", countries: [
    "Benin", "Burkina Faso", "Côte d’Ivoire", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"
  ], symbol: "Fr" },
  XPF: { name: "CFP Franc", iso2: "PF", iso3: "XPF", countries: ["French Polynesia", "New Caledonia", "Wallis and Futuna"], symbol: "₣" },
  YER: { name: "Yemeni Rial", iso2: "YE", iso3: "YER", countries: ["Yemen"], symbol: "﷼" },
  ZAR: { name: "South African Rand", iso2: "ZA", iso3: "ZAR", countries: ["South Africa"], symbol: "R" },
  ZMW: { name: "Zambian Kwacha", iso2: "ZM", iso3: "ZMW", countries: ["Zambia"], symbol: "ZK" },
  ZWL: { name: "Zimbabwean Dollar", iso2: "ZW", iso3: "ZWL", countries: ["Zimbabwe"], symbol: "$" },
};
export const allCurrencies = Object.values(currencyDetailsMap)
  .sort((a, b) => a.name.localeCompare(b.name))
